name: Workflow

on:
    push
jobs:
    image-builder:
        name: Checkout prerequisites and build image
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout current repo
                uses: actions/checkout@v3
            -
                name: Use the provided Dockerfile to build an image
                run: docker build -t smart_calc .
            -
                name: List docker images
                run: docker images

            - 
                name: Run the image (stepname)
                run: docker run -d --name smart_calc_container smart_calc
            -
                name: Execute scripts and log output
                run: |
                    docker exec my_container /bin/bash -c "./test.sh"
                    docker exec my_container /bin/bash -c "./build.sh run"
 
