name: Workflow

on:
    push
jobs:
    image-builder:
        name: Checkout prerequisites and build image
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout current repo
                uses: actions/checkout@v3
            -
                name: Use the provided Dockerfile to build an image
                run: docker build -t smart_calc .
            -
                name: List docker images
                run: docker images
    image-runner:
        name: Run the image (jobname)
        runs-on: ubuntu-latest
        needs: image-builder
        steps:
            -
                name: Run the image (stepname)
                run: docker run -it smart_calc

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v4
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       -
#         name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

