name: Workflow

on: 
  push
  

jobs:
  launch:
    runs-on: ubuntu-latest

    steps:
    - name: checkout current repo
      uses: actions/checkout@v3

    - name: launch prereqs.sh
      run: bash src/prereqs.sh
      
    - name: launch build.sh
      run: "src/build.sh all"
      shell: bash
      
    - name: launsh test.sh
      run: bash src/test.sh
